/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteUser200Response,
  FindStudent200Response,
  GetStudents200Response,
} from '../models';
import {
    DeleteUser200ResponseFromJSON,
    DeleteUser200ResponseToJSON,
    FindStudent200ResponseFromJSON,
    FindStudent200ResponseToJSON,
    GetStudents200ResponseFromJSON,
    GetStudents200ResponseToJSON,
} from '../models';

export interface DeleteStudentRequest {
    xTenantUID: string;
    id: number;
}

export interface FindStudentRequest {
    xTenantUID: string;
    id: number;
}

export interface GetStudentsRequest {
    xTenantUID: string;
    classroomId?: number;
    courseId?: number;
    number?: number;
}

/**
 * StudentApi - interface
 * 
 * @export
 * @interface StudentApiInterface
 */
export interface StudentApiInterface {
    /**
     * 
     * @summary 生徒削除
     * @param {string} xTenantUID テナント識別子
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApiInterface
     */
    deleteStudentRaw(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUser200Response>>;

    /**
     * 生徒削除
     */
    deleteStudent(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUser200Response>;

    /**
     * 
     * @summary 生徒単一取得
     * @param {string} xTenantUID テナント識別子
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApiInterface
     */
    findStudentRaw(requestParameters: FindStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindStudent200Response>>;

    /**
     * 生徒単一取得
     */
    findStudent(requestParameters: FindStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindStudent200Response>;

    /**
     * 
     * @summary 生徒一覧取得
     * @param {string} xTenantUID テナント識別子
     * @param {number} [classroomId] 
     * @param {number} [courseId] 
     * @param {number} [number] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StudentApiInterface
     */
    getStudentsRaw(requestParameters: GetStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStudents200Response>>;

    /**
     * 生徒一覧取得
     */
    getStudents(requestParameters: GetStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStudents200Response>;

}

/**
 * 
 */
export class StudentApi extends runtime.BaseAPI implements StudentApiInterface {

    /**
     * 生徒削除
     */
    async deleteStudentRaw(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUser200Response>> {
        if (requestParameters.xTenantUID === null || requestParameters.xTenantUID === undefined) {
            throw new runtime.RequiredError('xTenantUID','Required parameter requestParameters.xTenantUID was null or undefined when calling deleteStudent.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteStudent.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTenantUID !== undefined && requestParameters.xTenantUID !== null) {
            headerParameters['X-Tenant-UID'] = String(requestParameters.xTenantUID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/students/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteUser200ResponseFromJSON(jsonValue));
    }

    /**
     * 生徒削除
     */
    async deleteStudent(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUser200Response> {
        const response = await this.deleteStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 生徒単一取得
     */
    async findStudentRaw(requestParameters: FindStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindStudent200Response>> {
        if (requestParameters.xTenantUID === null || requestParameters.xTenantUID === undefined) {
            throw new runtime.RequiredError('xTenantUID','Required parameter requestParameters.xTenantUID was null or undefined when calling findStudent.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findStudent.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTenantUID !== undefined && requestParameters.xTenantUID !== null) {
            headerParameters['X-Tenant-UID'] = String(requestParameters.xTenantUID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/students/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindStudent200ResponseFromJSON(jsonValue));
    }

    /**
     * 生徒単一取得
     */
    async findStudent(requestParameters: FindStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindStudent200Response> {
        const response = await this.findStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 生徒一覧取得
     */
    async getStudentsRaw(requestParameters: GetStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStudents200Response>> {
        if (requestParameters.xTenantUID === null || requestParameters.xTenantUID === undefined) {
            throw new runtime.RequiredError('xTenantUID','Required parameter requestParameters.xTenantUID was null or undefined when calling getStudents.');
        }

        const queryParameters: any = {};

        if (requestParameters.classroomId !== undefined) {
            queryParameters['classroom-id'] = requestParameters.classroomId;
        }

        if (requestParameters.courseId !== undefined) {
            queryParameters['course-id'] = requestParameters.courseId;
        }

        if (requestParameters.number !== undefined) {
            queryParameters['number'] = requestParameters.number;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTenantUID !== undefined && requestParameters.xTenantUID !== null) {
            headerParameters['X-Tenant-UID'] = String(requestParameters.xTenantUID);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/students`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStudents200ResponseFromJSON(jsonValue));
    }

    /**
     * 生徒一覧取得
     */
    async getStudents(requestParameters: GetStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStudents200Response> {
        const response = await this.getStudentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
