/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Attendance } from './Attendance';
import {
    AttendanceFromJSON,
    AttendanceFromJSONTyped,
    AttendanceToJSON,
} from './Attendance';

/**
 * 
 * @export
 * @interface AttendancesIdDelete200Response
 */
export interface AttendancesIdDelete200Response {
    /**
     * 
     * @type {Attendance}
     * @memberof AttendancesIdDelete200Response
     */
    data?: Attendance;
}

/**
 * Check if a given object implements the AttendancesIdDelete200Response interface.
 */
export function instanceOfAttendancesIdDelete200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AttendancesIdDelete200ResponseFromJSON(json: any): AttendancesIdDelete200Response {
    return AttendancesIdDelete200ResponseFromJSONTyped(json, false);
}

export function AttendancesIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendancesIdDelete200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AttendanceFromJSON(json['data']),
    };
}

export function AttendancesIdDelete200ResponseToJSON(value?: AttendancesIdDelete200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AttendanceToJSON(value.data),
    };
}

