/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AttendancesIdDeleteRequest
 */
export interface AttendancesIdDeleteRequest {
  /**
   *
   * @type {boolean}
   * @memberof AttendancesIdDeleteRequest
   */
  attend?: boolean;
  /**
   *
   * @type {number}
   * @memberof AttendancesIdDeleteRequest
   */
  knowledge?: number;
  /**
   *
   * @type {number}
   * @memberof AttendancesIdDeleteRequest
   */
  expression?: number;
  /**
   *
   * @type {number}
   * @memberof AttendancesIdDeleteRequest
   */
  attitude?: number;
  /**
   *
   * @type {string}
   * @memberof AttendancesIdDeleteRequest
   */
  comment?: string;
}

/**
 * Check if a given object implements the AttendancesIdDeleteRequest interface.
 */
export function instanceOfAttendancesIdDeleteRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AttendancesIdDeleteRequestFromJSON(
  json: any
): AttendancesIdDeleteRequest {
  return AttendancesIdDeleteRequestFromJSONTyped(json, false);
}

export function AttendancesIdDeleteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AttendancesIdDeleteRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    attend: !exists(json, "attend") ? undefined : json["attend"],
    knowledge: !exists(json, "knowledge") ? undefined : json["knowledge"],
    expression: !exists(json, "expression") ? undefined : json["expression"],
    attitude: !exists(json, "attitude") ? undefined : json["attitude"],
    comment: !exists(json, "comment") ? undefined : json["comment"],
  };
}

export function AttendancesIdDeleteRequestToJSON(
  value?: AttendancesIdDeleteRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    attend: value.attend,
    knowledge: value.knowledge,
    expression: value.expression,
    attitude: value.attitude,
    comment: value.comment,
  };
}
