/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ClassroomWithCourse } from "./ClassroomWithCourse";
import {
  ClassroomWithCourseFromJSON,
  ClassroomWithCourseFromJSONTyped,
  ClassroomWithCourseToJSON,
} from "./ClassroomWithCourse";

/**
 *
 * @export
 * @interface ClassroomsIdDelete200Response
 */
export interface ClassroomsIdDelete200Response {
  /**
   *
   * @type {ClassroomWithCourse}
   * @memberof ClassroomsIdDelete200Response
   */
  data?: ClassroomWithCourse;
}

/**
 * Check if a given object implements the ClassroomsIdDelete200Response interface.
 */
export function instanceOfClassroomsIdDelete200Response(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ClassroomsIdDelete200ResponseFromJSON(
  json: any
): ClassroomsIdDelete200Response {
  return ClassroomsIdDelete200ResponseFromJSONTyped(json, false);
}

export function ClassroomsIdDelete200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClassroomsIdDelete200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : ClassroomWithCourseFromJSON(json["data"]),
  };
}

export function ClassroomsIdDelete200ResponseToJSON(
  value?: ClassroomsIdDelete200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ClassroomWithCourseToJSON(value.data),
  };
}
