/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Classroom } from './Classroom';
import {
    ClassroomFromJSON,
    ClassroomFromJSONTyped,
    ClassroomToJSON,
} from './Classroom';

/**
 * 
 * @export
 * @interface ClassroomGet200Response1
 */
export interface ClassroomGet200Response1 {
    /**
     * 
     * @type {Classroom}
     * @memberof ClassroomGet200Response1
     */
    data?: Classroom;
}

/**
 * Check if a given object implements the ClassroomGet200Response1 interface.
 */
export function instanceOfClassroomGet200Response1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClassroomGet200Response1FromJSON(json: any): ClassroomGet200Response1 {
    return ClassroomGet200Response1FromJSONTyped(json, false);
}

export function ClassroomGet200Response1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassroomGet200Response1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ClassroomFromJSON(json['data']),
    };
}

export function ClassroomGet200Response1ToJSON(value?: ClassroomGet200Response1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ClassroomToJSON(value.data),
    };
}

