/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassroomGetRequest
 */
export interface ClassroomGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ClassroomGetRequest
     */
    grade: number;
    /**
     * 
     * @type {string}
     * @memberof ClassroomGetRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClassroomGetRequest
     */
    teacher: string;
    /**
     * 生徒氏名リスト（出席番号順）
     * @type {Array<string>}
     * @memberof ClassroomGetRequest
     */
    student?: Array<string>;
}

/**
 * Check if a given object implements the ClassroomGetRequest interface.
 */
export function instanceOfClassroomGetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "grade" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "teacher" in value;

    return isInstance;
}

export function ClassroomGetRequestFromJSON(json: any): ClassroomGetRequest {
    return ClassroomGetRequestFromJSONTyped(json, false);
}

export function ClassroomGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassroomGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grade': json['grade'],
        'name': json['name'],
        'teacher': json['teacher'],
        'student': !exists(json, 'student') ? undefined : json['student'],
    };
}

export function ClassroomGetRequestToJSON(value?: ClassroomGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grade': value.grade,
        'name': value.name,
        'teacher': value.teacher,
        'student': value.student,
    };
}

