/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClassroomWithCourseCoursesInner } from './ClassroomWithCourseCoursesInner';
import {
    ClassroomWithCourseCoursesInnerFromJSON,
    ClassroomWithCourseCoursesInnerFromJSONTyped,
    ClassroomWithCourseCoursesInnerToJSON,
} from './ClassroomWithCourseCoursesInner';

/**
 * 
 * @export
 * @interface ClassroomWithCourse
 */
export interface ClassroomWithCourse {
    /**
     * 
     * @type {number}
     * @memberof ClassroomWithCourse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ClassroomWithCourse
     */
    grade: number;
    /**
     * 
     * @type {string}
     * @memberof ClassroomWithCourse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClassroomWithCourse
     */
    teacher: string;
    /**
     * 
     * @type {number}
     * @memberof ClassroomWithCourse
     */
    studentsCount: number;
    /**
     * 
     * @type {Array<ClassroomWithCourseCoursesInner>}
     * @memberof ClassroomWithCourse
     */
    courses: Array<ClassroomWithCourseCoursesInner>;
    /**
     * 
     * @type {Date}
     * @memberof ClassroomWithCourse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClassroomWithCourse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ClassroomWithCourse interface.
 */
export function instanceOfClassroomWithCourse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "grade" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "teacher" in value;
    isInstance = isInstance && "studentsCount" in value;
    isInstance = isInstance && "courses" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ClassroomWithCourseFromJSON(json: any): ClassroomWithCourse {
    return ClassroomWithCourseFromJSONTyped(json, false);
}

export function ClassroomWithCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassroomWithCourse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'grade': json['grade'],
        'name': json['name'],
        'teacher': json['teacher'],
        'studentsCount': json['studentsCount'],
        'courses': ((json['courses'] as Array<any>).map(ClassroomWithCourseCoursesInnerFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ClassroomWithCourseToJSON(value?: ClassroomWithCourse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'grade': value.grade,
        'name': value.name,
        'teacher': value.teacher,
        'studentsCount': value.studentsCount,
        'courses': ((value.courses as Array<any>).map(ClassroomWithCourseCoursesInnerToJSON)),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

