/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CourseLog } from "./CourseLog";
import {
  CourseLogFromJSON,
  CourseLogFromJSONTyped,
  CourseLogToJSON,
} from "./CourseLog";

/**
 *
 * @export
 * @interface CourseLogsGet200Response
 */
export interface CourseLogsGet200Response {
  /**
   *
   * @type {Array<CourseLog>}
   * @memberof CourseLogsGet200Response
   */
  data?: Array<CourseLog>;
}

/**
 * Check if a given object implements the CourseLogsGet200Response interface.
 */
export function instanceOfCourseLogsGet200Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CourseLogsGet200ResponseFromJSON(
  json: any
): CourseLogsGet200Response {
  return CourseLogsGet200ResponseFromJSONTyped(json, false);
}

export function CourseLogsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CourseLogsGet200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(CourseLogFromJSON),
  };
}

export function CourseLogsGet200ResponseToJSON(
  value?: CourseLogsGet200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(CourseLogToJSON),
  };
}
