/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Course } from "./Course";
import { CourseFromJSON, CourseFromJSONTyped, CourseToJSON } from "./Course";

/**
 *
 * @export
 * @interface CoursesGet200Response1
 */
export interface CoursesGet200Response1 {
  /**
   *
   * @type {Course}
   * @memberof CoursesGet200Response1
   */
  data?: Course;
}

/**
 * Check if a given object implements the CoursesGet200Response1 interface.
 */
export function instanceOfCoursesGet200Response1(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CoursesGet200Response1FromJSON(
  json: any
): CoursesGet200Response1 {
  return CoursesGet200Response1FromJSONTyped(json, false);
}

export function CoursesGet200Response1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CoursesGet200Response1 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data") ? undefined : CourseFromJSON(json["data"]),
  };
}

export function CoursesGet200Response1ToJSON(
  value?: CoursesGet200Response1 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: CourseToJSON(value.data),
  };
}
