/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CourseLogsIdDeleteRequest
 */
export interface CourseLogsIdDeleteRequest {
  /**
   *
   * @type {number}
   * @memberof CourseLogsIdDeleteRequest
   */
  courseId?: number;
  /**
   *
   * @type {Date}
   * @memberof CourseLogsIdDeleteRequest
   */
  date?: Date;
  /**
   *
   * @type {number}
   * @memberof CourseLogsIdDeleteRequest
   */
  period?: number;
}

/**
 * Check if a given object implements the CourseLogsIdDeleteRequest interface.
 */
export function instanceOfCourseLogsIdDeleteRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CourseLogsIdDeleteRequestFromJSON(
  json: any
): CourseLogsIdDeleteRequest {
  return CourseLogsIdDeleteRequestFromJSONTyped(json, false);
}

export function CourseLogsIdDeleteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CourseLogsIdDeleteRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    courseId: !exists(json, "courseId") ? undefined : json["courseId"],
    date: !exists(json, "date") ? undefined : new Date(json["date"]),
    period: !exists(json, "period") ? undefined : json["period"],
  };
}

export function CourseLogsIdDeleteRequestToJSON(
  value?: CourseLogsIdDeleteRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    courseId: value.courseId,
    date:
      value.date === undefined
        ? undefined
        : value.date.toISOString().substr(0, 10),
    period: value.period,
  };
}
