/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseLogsGetRequestAttendancesInner } from './CourseLogsGetRequestAttendancesInner';
import {
    CourseLogsGetRequestAttendancesInnerFromJSON,
    CourseLogsGetRequestAttendancesInnerFromJSONTyped,
    CourseLogsGetRequestAttendancesInnerToJSON,
} from './CourseLogsGetRequestAttendancesInner';

/**
 * 
 * @export
 * @interface CourseLogsGetRequest
 */
export interface CourseLogsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseLogsGetRequest
     */
    courseId: number;
    /**
     * 
     * @type {Date}
     * @memberof CourseLogsGetRequest
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof CourseLogsGetRequest
     */
    period: number;
    /**
     * 
     * @type {Array<CourseLogsGetRequestAttendancesInner>}
     * @memberof CourseLogsGetRequest
     */
    attendances: Array<CourseLogsGetRequestAttendancesInner>;
}

/**
 * Check if a given object implements the CourseLogsGetRequest interface.
 */
export function instanceOfCourseLogsGetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courseId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "period" in value;
    isInstance = isInstance && "attendances" in value;

    return isInstance;
}

export function CourseLogsGetRequestFromJSON(json: any): CourseLogsGetRequest {
    return CourseLogsGetRequestFromJSONTyped(json, false);
}

export function CourseLogsGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseLogsGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseId': json['courseId'],
        'date': (new Date(json['date'])),
        'period': json['period'],
        'attendances': ((json['attendances'] as Array<any>).map(CourseLogsGetRequestAttendancesInnerFromJSON)),
    };
}

export function CourseLogsGetRequestToJSON(value?: CourseLogsGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseId': value.courseId,
        'date': (value.date.toISOString().substr(0,10)),
        'period': value.period,
        'attendances': ((value.attendances as Array<any>).map(CourseLogsGetRequestAttendancesInnerToJSON)),
    };
}

