/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Course } from './Course';
import {
    CourseFromJSON,
    CourseFromJSONTyped,
    CourseToJSON,
} from './Course';

/**
 * 
 * @export
 * @interface CoursesGet200Response
 */
export interface CoursesGet200Response {
    /**
     * 
     * @type {Array<Course>}
     * @memberof CoursesGet200Response
     */
    data?: Array<Course>;
}

/**
 * Check if a given object implements the CoursesGet200Response interface.
 */
export function instanceOfCoursesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CoursesGet200ResponseFromJSON(json: any): CoursesGet200Response {
    return CoursesGet200ResponseFromJSONTyped(json, false);
}

export function CoursesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoursesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CourseFromJSON)),
    };
}

export function CoursesGet200ResponseToJSON(value?: CoursesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CourseToJSON)),
    };
}

