/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Course } from './Course';
import {
    CourseFromJSON,
    CourseFromJSONTyped,
    CourseToJSON,
} from './Course';

/**
 * 
 * @export
 * @interface FindCourse200Response
 */
export interface FindCourse200Response {
    /**
     * 
     * @type {Course}
     * @memberof FindCourse200Response
     */
    data: Course;
}

/**
 * Check if a given object implements the FindCourse200Response interface.
 */
export function instanceOfFindCourse200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function FindCourse200ResponseFromJSON(json: any): FindCourse200Response {
    return FindCourse200ResponseFromJSONTyped(json, false);
}

export function FindCourse200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindCourse200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CourseFromJSON(json['data']),
    };
}

export function FindCourse200ResponseToJSON(value?: FindCourse200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CourseToJSON(value.data),
    };
}

