/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
} from './Schedule';

/**
 * 
 * @export
 * @interface FindSchedule200Response
 */
export interface FindSchedule200Response {
    /**
     * 
     * @type {Schedule}
     * @memberof FindSchedule200Response
     */
    data: Schedule;
}

/**
 * Check if a given object implements the FindSchedule200Response interface.
 */
export function instanceOfFindSchedule200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function FindSchedule200ResponseFromJSON(json: any): FindSchedule200Response {
    return FindSchedule200ResponseFromJSONTyped(json, false);
}

export function FindSchedule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindSchedule200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ScheduleFromJSON(json['data']),
    };
}

export function FindSchedule200ResponseToJSON(value?: FindSchedule200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ScheduleToJSON(value.data),
    };
}

