/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Attendance } from './Attendance';
import {
    AttendanceFromJSON,
    AttendanceFromJSONTyped,
    AttendanceToJSON,
} from './Attendance';

/**
 * 
 * @export
 * @interface GetAttendances200Response
 */
export interface GetAttendances200Response {
    /**
     * 
     * @type {Array<Attendance>}
     * @memberof GetAttendances200Response
     */
    data: Array<Attendance>;
}

/**
 * Check if a given object implements the GetAttendances200Response interface.
 */
export function instanceOfGetAttendances200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetAttendances200ResponseFromJSON(json: any): GetAttendances200Response {
    return GetAttendances200ResponseFromJSONTyped(json, false);
}

export function GetAttendances200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAttendances200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AttendanceFromJSON)),
    };
}

export function GetAttendances200ResponseToJSON(value?: GetAttendances200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AttendanceToJSON)),
    };
}

