/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCourseLogsRequestAttendancesInner } from './GetCourseLogsRequestAttendancesInner';
import {
    GetCourseLogsRequestAttendancesInnerFromJSON,
    GetCourseLogsRequestAttendancesInnerFromJSONTyped,
    GetCourseLogsRequestAttendancesInnerToJSON,
} from './GetCourseLogsRequestAttendancesInner';

/**
 * 
 * @export
 * @interface GetCourseLogsRequest
 */
export interface GetCourseLogsRequest {
    /**
     * 
     * @type {number}
     * @memberof GetCourseLogsRequest
     */
    courseId: number;
    /**
     * 
     * @type {Date}
     * @memberof GetCourseLogsRequest
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof GetCourseLogsRequest
     */
    period: number;
    /**
     * 
     * @type {Array<GetCourseLogsRequestAttendancesInner>}
     * @memberof GetCourseLogsRequest
     */
    attendances: Array<GetCourseLogsRequestAttendancesInner>;
}

/**
 * Check if a given object implements the GetCourseLogsRequest interface.
 */
export function instanceOfGetCourseLogsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courseId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "period" in value;
    isInstance = isInstance && "attendances" in value;

    return isInstance;
}

export function GetCourseLogsRequestFromJSON(json: any): GetCourseLogsRequest {
    return GetCourseLogsRequestFromJSONTyped(json, false);
}

export function GetCourseLogsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCourseLogsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseId': json['courseId'],
        'date': (new Date(json['date'])),
        'period': json['period'],
        'attendances': ((json['attendances'] as Array<any>).map(GetCourseLogsRequestAttendancesInnerFromJSON)),
    };
}

export function GetCourseLogsRequestToJSON(value?: GetCourseLogsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseId': value.courseId,
        'date': (value.date.toISOString().substr(0,10)),
        'period': value.period,
        'attendances': ((value.attendances as Array<any>).map(GetCourseLogsRequestAttendancesInnerToJSON)),
    };
}

