/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseLog } from './CourseLog';
import {
    CourseLogFromJSON,
    CourseLogFromJSONTyped,
    CourseLogToJSON,
} from './CourseLog';

/**
 * 
 * @export
 * @interface GetCourseLogs200Response
 */
export interface GetCourseLogs200Response {
    /**
     * 
     * @type {Array<CourseLog>}
     * @memberof GetCourseLogs200Response
     */
    data: Array<CourseLog>;
}

/**
 * Check if a given object implements the GetCourseLogs200Response interface.
 */
export function instanceOfGetCourseLogs200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCourseLogs200ResponseFromJSON(json: any): GetCourseLogs200Response {
    return GetCourseLogs200ResponseFromJSONTyped(json, false);
}

export function GetCourseLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCourseLogs200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CourseLogFromJSON)),
    };
}

export function GetCourseLogs200ResponseToJSON(value?: GetCourseLogs200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CourseLogToJSON)),
    };
}

