/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Score } from './Score';
import {
    ScoreFromJSON,
    ScoreFromJSONTyped,
    ScoreToJSON,
} from './Score';

/**
 * 
 * @export
 * @interface GetScores200Response
 */
export interface GetScores200Response {
    /**
     * 
     * @type {Array<Score>}
     * @memberof GetScores200Response
     */
    data?: Array<Score>;
}

/**
 * Check if a given object implements the GetScores200Response interface.
 */
export function instanceOfGetScores200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetScores200ResponseFromJSON(json: any): GetScores200Response {
    return GetScores200ResponseFromJSONTyped(json, false);
}

export function GetScores200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetScores200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ScoreFromJSON)),
    };
}

export function GetScores200ResponseToJSON(value?: GetScores200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ScoreToJSON)),
    };
}

