/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationsGetRequest
 */
export interface InvitationsGetRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitationsGetRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the InvitationsGetRequest interface.
 */
export function instanceOfInvitationsGetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InvitationsGetRequestFromJSON(json: any): InvitationsGetRequest {
    return InvitationsGetRequestFromJSONTyped(json, false);
}

export function InvitationsGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationsGetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function InvitationsGetRequestToJSON(value?: InvitationsGetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

