/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IpAddressesGetRequest
 */
export interface IpAddressesGetRequest {
  /**
   *
   * @type {string}
   * @memberof IpAddressesGetRequest
   */
  ip: string;
  /**
   *
   * @type {string}
   * @memberof IpAddressesGetRequest
   */
  label?: string;
}

/**
 * Check if a given object implements the IpAddressesGetRequest interface.
 */
export function instanceOfIpAddressesGetRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "ip" in value;

  return isInstance;
}

export function IpAddressesGetRequestFromJSON(
  json: any
): IpAddressesGetRequest {
  return IpAddressesGetRequestFromJSONTyped(json, false);
}

export function IpAddressesGetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IpAddressesGetRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ip: json["ip"],
    label: !exists(json, "label") ? undefined : json["label"],
  };
}

export function IpAddressesGetRequestToJSON(
  value?: IpAddressesGetRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ip: value.ip,
    label: value.label,
  };
}
