/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ClientIp } from "./ClientIp";
import {
  ClientIpFromJSON,
  ClientIpFromJSONTyped,
  ClientIpToJSON,
} from "./ClientIp";

/**
 *
 * @export
 * @interface IpAddressesGet200Response1
 */
export interface IpAddressesGet200Response1 {
  /**
   *
   * @type {ClientIp}
   * @memberof IpAddressesGet200Response1
   */
  data?: ClientIp;
}

/**
 * Check if a given object implements the IpAddressesGet200Response1 interface.
 */
export function instanceOfIpAddressesGet200Response1(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IpAddressesGet200Response1FromJSON(
  json: any
): IpAddressesGet200Response1 {
  return IpAddressesGet200Response1FromJSONTyped(json, false);
}

export function IpAddressesGet200Response1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IpAddressesGet200Response1 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data") ? undefined : ClientIpFromJSON(json["data"]),
  };
}

export function IpAddressesGet200Response1ToJSON(
  value?: IpAddressesGet200Response1 | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ClientIpToJSON(value.data),
  };
}
