/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface IPAddress
 */
export interface IPAddress {
    /**
     * 
     * @type {number}
     * @memberof IPAddress
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    label?: string;
    /**
     * 
     * @type {User}
     * @memberof IPAddress
     */
    createdBy?: User;
    /**
     * 
     * @type {User}
     * @memberof IPAddress
     */
    updatedBy?: User;
    /**
     * 
     * @type {Date}
     * @memberof IPAddress
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof IPAddress
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the IPAddress interface.
 */
export function instanceOfIPAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "ip" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function IPAddressFromJSON(json: any): IPAddress {
    return IPAddressFromJSONTyped(json, false);
}

export function IPAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ip': json['ip'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'createdBy': !exists(json, 'createdBy') ? undefined : UserFromJSON(json['createdBy']),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : UserFromJSON(json['updatedBy']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function IPAddressToJSON(value?: IPAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ip': value.ip,
        'label': value.label,
        'createdBy': UserToJSON(value.createdBy),
        'updatedBy': UserToJSON(value.updatedBy),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

