/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClientIp } from './ClientIp';
import {
    ClientIpFromJSON,
    ClientIpFromJSONTyped,
    ClientIpToJSON,
} from './ClientIp';

/**
 * 
 * @export
 * @interface IpAddressesGet200Response
 */
export interface IpAddressesGet200Response {
    /**
     * 
     * @type {Array<ClientIp>}
     * @memberof IpAddressesGet200Response
     */
    data?: Array<ClientIp>;
}

/**
 * Check if a given object implements the IpAddressesGet200Response interface.
 */
export function instanceOfIpAddressesGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IpAddressesGet200ResponseFromJSON(json: any): IpAddressesGet200Response {
    return IpAddressesGet200ResponseFromJSONTyped(json, false);
}

export function IpAddressesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpAddressesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ClientIpFromJSON)),
    };
}

export function IpAddressesGet200ResponseToJSON(value?: IpAddressesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ClientIpToJSON)),
    };
}

