/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostInvitationRequest
 */
export interface PostInvitationRequest {
    /**
     * 
     * @type {string}
     * @memberof PostInvitationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the PostInvitationRequest interface.
 */
export function instanceOfPostInvitationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function PostInvitationRequestFromJSON(json: any): PostInvitationRequest {
    return PostInvitationRequestFromJSONTyped(json, false);
}

export function PostInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostInvitationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function PostInvitationRequestToJSON(value?: PostInvitationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

