/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostIpAddressRequest
 */
export interface PostIpAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof PostIpAddressRequest
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof PostIpAddressRequest
     */
    label?: string;
}

/**
 * Check if a given object implements the PostIpAddressRequest interface.
 */
export function instanceOfPostIpAddressRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ip" in value;

    return isInstance;
}

export function PostIpAddressRequestFromJSON(json: any): PostIpAddressRequest {
    return PostIpAddressRequestFromJSONTyped(json, false);
}

export function PostIpAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostIpAddressRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ip': json['ip'],
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}

export function PostIpAddressRequestToJSON(value?: PostIpAddressRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ip': value.ip,
        'label': value.label,
    };
}

