/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
} from './Schedule';

/**
 * 
 * @export
 * @interface PostSchedule200Response
 */
export interface PostSchedule200Response {
    /**
     * 
     * @type {Schedule}
     * @memberof PostSchedule200Response
     */
    data?: Schedule;
}

/**
 * Check if a given object implements the PostSchedule200Response interface.
 */
export function instanceOfPostSchedule200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostSchedule200ResponseFromJSON(json: any): PostSchedule200Response {
    return PostSchedule200ResponseFromJSONTyped(json, false);
}

export function PostSchedule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSchedule200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ScheduleFromJSON(json['data']),
    };
}

export function PostSchedule200ResponseToJSON(value?: PostSchedule200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ScheduleToJSON(value.data),
    };
}

