/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostScheduleRequest
 */
export interface PostScheduleRequest {
    /**
     * 
     * @type {number}
     * @memberof PostScheduleRequest
     */
    classroomId?: number;
    /**
     * 
     * @type {number}
     * @memberof PostScheduleRequest
     */
    subjectId?: number;
    /**
     * 1-7 or mon-sun or 月-日
     * @type {string}
     * @memberof PostScheduleRequest
     */
    day?: string;
    /**
     * 
     * @type {number}
     * @memberof PostScheduleRequest
     */
    period?: number;
}

/**
 * Check if a given object implements the PostScheduleRequest interface.
 */
export function instanceOfPostScheduleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostScheduleRequestFromJSON(json: any): PostScheduleRequest {
    return PostScheduleRequestFromJSONTyped(json, false);
}

export function PostScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostScheduleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classroomId': !exists(json, 'classroomId') ? undefined : json['classroomId'],
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'day': !exists(json, 'day') ? undefined : json['day'],
        'period': !exists(json, 'period') ? undefined : json['period'],
    };
}

export function PostScheduleRequestToJSON(value?: PostScheduleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classroomId': value.classroomId,
        'subjectId': value.subjectId,
        'day': value.day,
        'period': value.period,
    };
}

