/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IPAddress } from './IPAddress';
import {
    IPAddressFromJSON,
    IPAddressFromJSONTyped,
    IPAddressToJSON,
} from './IPAddress';

/**
 * 
 * @export
 * @interface PostIpAddress200Response
 */
export interface PostIpAddress200Response {
    /**
     * 
     * @type {IPAddress}
     * @memberof PostIpAddress200Response
     */
    data?: IPAddress;
}

/**
 * Check if a given object implements the PostIpAddress200Response interface.
 */
export function instanceOfPostIpAddress200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostIpAddress200ResponseFromJSON(json: any): PostIpAddress200Response {
    return PostIpAddress200ResponseFromJSONTyped(json, false);
}

export function PostIpAddress200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostIpAddress200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : IPAddressFromJSON(json['data']),
    };
}

export function PostIpAddress200ResponseToJSON(value?: PostIpAddress200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': IPAddressToJSON(value.data),
    };
}

