/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostClassroomRequest
 */
export interface PostClassroomRequest {
    /**
     * 
     * @type {number}
     * @memberof PostClassroomRequest
     */
    grade: number;
    /**
     * 
     * @type {string}
     * @memberof PostClassroomRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PostClassroomRequest
     */
    teacher: string;
    /**
     * 生徒氏名リスト（出席番号順）
     * @type {Array<string>}
     * @memberof PostClassroomRequest
     */
    students: Array<string>;
}

/**
 * Check if a given object implements the PostClassroomRequest interface.
 */
export function instanceOfPostClassroomRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "grade" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "teacher" in value;
    isInstance = isInstance && "students" in value;

    return isInstance;
}

export function PostClassroomRequestFromJSON(json: any): PostClassroomRequest {
    return PostClassroomRequestFromJSONTyped(json, false);
}

export function PostClassroomRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostClassroomRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grade': json['grade'],
        'name': json['name'],
        'teacher': json['teacher'],
        'students': json['students'],
    };
}

export function PostClassroomRequestToJSON(value?: PostClassroomRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grade': value.grade,
        'name': value.name,
        'teacher': value.teacher,
        'students': value.students,
    };
}

