/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
} from './Student';

/**
 * 
 * @export
 * @interface StudentsIdDelete200Response
 */
export interface StudentsIdDelete200Response {
    /**
     * 
     * @type {Student}
     * @memberof StudentsIdDelete200Response
     */
    data?: Student;
}

/**
 * Check if a given object implements the StudentsIdDelete200Response interface.
 */
export function instanceOfStudentsIdDelete200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentsIdDelete200ResponseFromJSON(json: any): StudentsIdDelete200Response {
    return StudentsIdDelete200ResponseFromJSONTyped(json, false);
}

export function StudentsIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentsIdDelete200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : StudentFromJSON(json['data']),
    };
}

export function StudentsIdDelete200ResponseToJSON(value?: StudentsIdDelete200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StudentToJSON(value.data),
    };
}

