/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Classroom } from "./Classroom";
import {
  ClassroomFromJSON,
  ClassroomFromJSONTyped,
  ClassroomToJSON,
} from "./Classroom";

/**
 *
 * @export
 * @interface Student
 */
export interface Student {
  /**
   *
   * @type {number}
   * @memberof Student
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Student
   */
  number: number;
  /**
   *
   * @type {string}
   * @memberof Student
   */
  name: string;
  /**
   *
   * @type {Classroom}
   * @memberof Student
   */
  classroom: Classroom;
  /**
   *
   * @type {Date}
   * @memberof Student
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Student
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the Student interface.
 */
export function instanceOfStudent(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "number" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "classroom" in value;
  isInstance = isInstance && "createdAt" in value;

  return isInstance;
}

export function StudentFromJSON(json: any): Student {
  return StudentFromJSONTyped(json, false);
}

export function StudentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Student {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    number: json["number"],
    name: json["name"],
    classroom: ClassroomFromJSON(json["classroom"]),
    createdAt: new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
  };
}

export function StudentToJSON(value?: Student | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    number: value.number,
    name: value.name,
    classroom: ClassroomToJSON(value.classroom),
    createdAt: value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
  };
}
