/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * 出席くんAPI
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: tkc@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseLog } from './CourseLog';
import {
    CourseLogFromJSON,
    CourseLogFromJSONTyped,
    CourseLogToJSON,
} from './CourseLog';

/**
 * 
 * @export
 * @interface UpdateCourseLog200Response
 */
export interface UpdateCourseLog200Response {
    /**
     * 
     * @type {CourseLog}
     * @memberof UpdateCourseLog200Response
     */
    data?: CourseLog;
}

/**
 * Check if a given object implements the UpdateCourseLog200Response interface.
 */
export function instanceOfUpdateCourseLog200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateCourseLog200ResponseFromJSON(json: any): UpdateCourseLog200Response {
    return UpdateCourseLog200ResponseFromJSONTyped(json, false);
}

export function UpdateCourseLog200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCourseLog200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CourseLogFromJSON(json['data']),
    };
}

export function UpdateCourseLog200ResponseToJSON(value?: UpdateCourseLog200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CourseLogToJSON(value.data),
    };
}

