/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UsersIdDelete200Response
 */
export interface UsersIdDelete200Response {
  /**
   * 削除されたID
   * @type {number}
   * @memberof UsersIdDelete200Response
   */
  data?: number;
}

/**
 * Check if a given object implements the UsersIdDelete200Response interface.
 */
export function instanceOfUsersIdDelete200Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersIdDelete200ResponseFromJSON(
  json: any
): UsersIdDelete200Response {
  return UsersIdDelete200ResponseFromJSONTyped(json, false);
}

export function UsersIdDelete200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersIdDelete200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data") ? undefined : json["data"],
  };
}

export function UsersIdDelete200ResponseToJSON(
  value?: UsersIdDelete200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data,
  };
}
