/* tslint:disable */
/* eslint-disable */
/**
 * 出席くんAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { User } from "./User";
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from "./User";

/**
 *
 * @export
 * @interface UsersCurrentGet200Response
 */
export interface UsersCurrentGet200Response {
  /**
   *
   * @type {User}
   * @memberof UsersCurrentGet200Response
   */
  data?: User;
}

/**
 * Check if a given object implements the UsersCurrentGet200Response interface.
 */
export function instanceOfUsersCurrentGet200Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersCurrentGet200ResponseFromJSON(
  json: any
): UsersCurrentGet200Response {
  return UsersCurrentGet200ResponseFromJSONTyped(json, false);
}

export function UsersCurrentGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersCurrentGet200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data") ? undefined : UserFromJSON(json["data"]),
  };
}

export function UsersCurrentGet200ResponseToJSON(
  value?: UsersCurrentGet200Response | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UserToJSON(value.data),
  };
}
